- alias: Turn bedroom lights on with wall remote Ch1 or Normal Remote Ch1
  trigger:
    - event_type: button_pressed
      platform: event
      event_data:
        entity_id: switch.bedroom_wall_switch_ch1
        state: 'on'
    - event_type: button_pressed
      platform: event
      event_data:
        entity_id: switch.bedroom_remote_ch1
        state: 'on'
  condition: []
  action:
    - service: light.turn_on
      data:
        entity_id:
        - light.bedlight_elze
        - light.bedlight_jolande
        - light.bedroom_standing_light

- alias: Turn bedroom lights and TV off with wall remote Ch1 or Normal Remote Ch1
  trigger:
    - event_type: button_pressed
      platform: event
      event_data:
        entity_id: switch.bedroom_wall_switch_ch1
        state: 'off'
    - event_type: button_pressed
      platform: event
      event_data:
        entity_id: switch.bedroom_remote_ch1
        state: 'off'
  condition: []
  action:
    - service: light.turn_off
      data:
        entity_id:
        - light.bedlight_elze
        - light.bedlight_jolande
        - light.bedroom_standing_light
    - service: switch.turn_off
      data:
        entity_id:
        - switch.bedroom_remote_ch2

- alias: Turn bedroom lights on full with wall remote Ch2 or Normal Remote Ch3
  trigger:
    - event_type: button_pressed
      platform: event
      event_data:
        entity_id: switch.bedroom_wall_switch_ch2
        state: 'on'
    - event_type: button_pressed
      platform: event
      event_data:
        entity_id: switch.bedroom_remote_ch3
        state: 'on'
  condition: []
  action:
    - service: light.turn_on
      data:
        brightness: 254
        color_temp: 250
        entity_id:
        - light.bedlight_elze
        - light.bedlight_jolande
        - light.bedroom_standing_light

- alias: Turn bedroom lights on dimmed with wall remote Ch2 or Normal Remote Ch3
  trigger:
    - event_type: button_pressed
      platform: event
      event_data:
        entity_id: switch.bedroom_wall_switch_ch2
        state: 'off'
    - event_type: button_pressed
      platform: event
      event_data:
        entity_id: switch.bedroom_remote_ch3
        state: 'off'
  condition: []
  action:
    - service: light.turn_on
      data:
        brightness: 40
        color_temp: 368
        entity_id:
        - light.bedlight_elze
        - light.bedlight_jolande
        - light.bedroom_standing_light        