# Home assitant base configuration
homeassistant:
  name: !secret home_name
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: 0
  unit_system: metric
  time_zone: Europe/Amsterdam
  customize: !include customize.yaml

# Frontend configuration
frontend:
  themes:
    dark:
      primary-color: "#263238"

# HTTP configuration
http:
  base_url: !secret http_base_url
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem
  ip_ban_enabled: true
  login_attempts_threshold: 10
  trusted_networks:
      - 192.168.0.107/32
      - 192.168.0.183/32
      
# Checks for available updates
updater:
  include_used_components: true

# Discover some devices automatically
discovery:

# Enable configuration
config:

# Configure notifications
notify:
  - platform: html5
    gcm_api_key: !secret notify_gcm_api_key
    gcm_sender_id: !secret notify_gcm_sender_id

# History recorder
recorder:
  purge_keep_days: 5
  purge_interval: 1
  include:
    entities:
      - climate.toon_van_eneco
      - sensor.br_humidity
      - sensor.br_symbol
      - sensor.br_temperature
      - sensor.power_current
      - sensor.power_today
      - sensor.gas_current
      - sensor.gas_today  

# History display
history:
  include:
    entities:
      - climate.toon_van_eneco
      - sensor.br_humidity
      - sensor.br_symbol
      - sensor.br_temperature
      - sensor.power_current
      - sensor.power_today
      - sensor.gas_current
      - sensor.gas_today

# Track the sun
sun:

# Weather prediction
sensor:
  - platform: buienradar
    monitored_conditions:
      - symbol
      - humidity
      - temperature
  - platform: time_date
    display_options:
      - date
      - time
  - platform: template
    sensors:
      toon_current_temperature:
        unit_of_measurement: 'C'
        value_template: "{{ states.climate.toon_van_eneco.attributes.current_temperature }}"

# Cloud
cloud:
  alexa: !include alexa.yaml
  google_actions: !include googlehome.yaml

# Eneco Toon
toon:
  username: !secret toon_username
  password: !secret toon_password
  consumer_key: !secret toon_consumer_key
  consumer_secret: !secret toon_consumer_secret

# RFXCom Hub
rfxtrx:
  device: /dev/ttyUSB0

# Switches
switch:
  - platform: rfxtrx
    automatic_add: false
    devices: !include rfxtrx/switches.yaml

  - platform: template
    switches:    
    
      # Create special All Lego switch
      all_lego:
        value_template: "{{ is_state('switch.lego_bookcase', 'on') or is_state('switch.lego_above_desk', 'on') or is_state('switch.lego_window_side', 'on') or is_state('switch.lego_starwars', 'on') or is_state('switch.lego_display_boxes', 'on') }}"
        turn_on:
          service: switch.turn_on
          data:
            entity_id:
              - switch.lego_above_desk
              - switch.lego_window_side
              - switch.lego_starwars
              - switch.lego_display_boxes
              - switch.lego_bookcase
        turn_off:
          service: switch.turn_off
          data:
            entity_id:
              - switch.lego_above_desk
              - switch.lego_window_side
              - switch.lego_starwars
              - switch.lego_display_boxes
              - switch.lego_bookcase
      
# Light configuration
light:
  - platform: group
    name: Hobby ceiling lights
    entities:
      - light.hobby_elze_ceiling_light_1
      - light.hobby_elze_ceiling_light_2
      
  - platform: group
    name: Kitchen ceiling lights
    entities:
      - light.kitchen_light_1
      - light.kitchen_light_2
      - light.kitchen_light_3
      
  - platform: group
    name: Livingroom Standing Light
    entities:
      - light.livingroom_standing_light_down
      - light.livingroom_standing_light_up_1
      - light.livingroom_standing_light_up_2

  - platform: rfxtrx
    automatic_add: false
    devices: !include rfxtrx/lights.yaml


input_select: !include automation_util/input_select.yaml
group: !include groups.yaml
automation: !include_dir_merge_list automations
script: !include_dir_merge_named scripts
